### ISSUE TITLE
Conscious Language: Please rename master branch to main branch

### ISSUE THREAD

**Issue by nhosoi** [linux-system-roles/selinux#137]
As part of the conscious language project, the master branch is to be renamed to the main branch.

Here are the instructions.

1. Rename the master branch to main: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch
2. Check this to ensure the default branch has been changed to main: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch - this should keep the github history, as well as updating the default branch configuration and updating any existing PRs

If you use the gh cli (highly recommended) you can use this to check which repos need to be updated:
```
gh repo list linux-system-roles -L 100 --json name,defaultBranchRef --source | \
  jq --raw-output '.[] | select(.defaultBranchRef.name == "master") | .name'
```
Thanks.

**Comment by bachradsusi** [comment]
Is there a way to rename the `master` branch to `main` but leave (at least for some time) `master` as an alias of `main`?

**Comment by bachradsusi** [comment]
Some kind of backward compatibility for transition period. In other project we hit problem that different test infrastructures used hardcoded `master` branch.

I didn't mean this as no to change but I was more curious whether there's such option also for other project I'm  involved in.

**Comment by bachradsusi** [comment]
Yes, lets do it.

**Comment by richm** [comment]
done
"The default branch has been renamed!

master is now named main

If you have a local clone, you can update it by running the following commands.
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
"
