### ISSUE TITLE
defined selinux_ports cause error when selinux_state=disabled

### ISSUE THREAD

**Issue by goshansp** [linux-system-roles/selinux#188]
Setting `selinux_ports` will cause the module to fail if  `selinux_state=disabled`. We require to set `selinux_ports` globally.

Workaround: Setting `selinux_ports=[]` for all hosts that `selinux_state=disabled` and hence bloating the inventory.

Is there a way to avoid this without PR?

**Comment by bachradsusi** [comment]
"seport" module has "ignore_selinux_state" option:

```
- ignore_selinux_state
        Run independent of selinux runtime state
        default: false
        type: bool
```

Using the following change it's possible to set SELinux port mapping on a system with SELinux disabled but with installed "selinux-policy-targeted"

```
diff --git a/tasks/main.yml b/tasks/main.yml
index f78f8a18ab1e..6da1a674d7e1 100644
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@ -102,6 +102,7 @@
     setype: "{{ item.setype }}"
     state: "{{ item.state | default('present') }}"
     local: "{{ item.local | default(False) }}"
+    ignore_selinux_state: "{{ selinux_state != 'disabled' }}"
   with_items: "{{ selinux_ports }}"
 
 - name: Set linux user to SELinux user mapping
 ```

**Comment by bachradsusi** [comment]
Please hold this PR for now. I'll probably make another change booleans settings, Something like the following change could improve the role for SELinux disabled mode. I'm working also on seboolean module change for this.

```
diff --git a/tasks/main.yml b/tasks/main.yml
index 5cd0ee23efda..9c35a5ecb8a3 100644
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@ -68,7 +68,8 @@
   seboolean:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
-    persistent: "{{ item.persistent | default('no') }}"
+    persistent: "{{ item.persistent \
+                  | default( ansible_selinux.status == 'disabled' ) }}"
     ignore_selinux_state: "{{ ansible_selinux.status == 'disabled' }}"
   with_items: "{{ selinux_booleans }}"
 
```
