### ISSUE TITLE
Create tests for selinux_*_purge variables

### ISSUE THREAD

**Issue by wrabcak** [linux-system-roles/selinux#21]
selinux_*_purge variables was added to SELinux role. We should have tests if local modifications are defined that appropriate semanage sub-command drop it. 

More info #16

**Comment by wrabcak** [comment]
Following Pull Request updates current tests.
#22

**Comment by wrabcak** [comment]
Also #25  should fix the issue.

**Comment by wrabcak** [comment]
I think we can close this issue besed on #22 and #25

**Comment by pcahyna** [comment]
one more test: #29
