### ISSUE TITLE
`test_selinux_disabled` fails on centos-6

### ISSUE THREAD

**Issue by larskarlitski** [linux-system-roles/selinux#3]
```
TASK [selinux : Drop all local modifications] **********************************
task path: /role/tasks/main.yml:25
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/commands/command.py
<localhost> ESTABLISH SSH CONNECTION FOR USER: admin
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'IdentityFile="/var/tmp/avocado_zrDGNN/3-test.py_Test.test_3/tmpEDB8PZ/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=admin -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlPath=/home/tester/.ansible/cp/ansible-ssh-%h-%p-%r localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1504016091.84-192915026227876 `" && echo ansible-tmp-1504016091.84-192915026227876="` echo ~/.ansible/tmp/ansible-tmp-1504016091.84-192915026227876 `" ) && sleep 0'"'"''
<localhost> PUT /var/tmp/tmp5g6jvq TO /home/admin/.ansible/tmp/ansible-tmp-1504016091.84-192915026227876/command.py
<localhost> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'IdentityFile="/var/tmp/avocado_zrDGNN/3-test.py_Test.test_3/tmpEDB8PZ/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=admin -o ConnectTimeout=10 -o ControlPath=/home/tester/.ansible/cp/ansible-ssh-%h-%p-%r '[localhost]'
<localhost> ESTABLISH SSH CONNECTION FOR USER: admin
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'IdentityFile="/var/tmp/avocado_zrDGNN/3-test.py_Test.test_3/tmpEDB8PZ/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=admin -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlPath=/home/tester/.ansible/cp/ansible-ssh-%h-%p-%r localhost '/bin/sh -c '"'"'chmod u+x /home/admin/.ansible/tmp/ansible-tmp-1504016091.84-192915026227876/ /home/admin/.ansible/tmp/ansible-tmp-1504016091.84-192915026227876/command.py && sleep 0'"'"''
<localhost> ESTABLISH SSH CONNECTION FOR USER: admin
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'IdentityFile="/var/tmp/avocado_zrDGNN/3-test.py_Test.test_3/tmpEDB8PZ/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=admin -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlPath=/home/tester/.ansible/cp/ansible-ssh-%h-%p-%r -tt localhost '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-ypnvflynfxwpvicevgrxxvjbhncfyqvo; /usr/bin/python /home/admin/.ansible/tmp/ansible-tmp-1504016091.84-192915026227876/command.py; rm -rf "/home/admin/.ansible/tmp/ansible-tmp-1504016091.84-192915026227876/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [system-api-test]: FAILED! => {
    "changed": true, 
    "cmd": "echo \"boolean -D -N\nlogin -D -N\nport -D -N\nfcontext -D -N\n\" | /usr/sbin/semanage -i -", 
    "delta": "0:00:23.136689", 
    "end": "2017-08-29 14:15:14.567518", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "echo \"boolean -D -N\nlogin -D -N\nport -D -N\nfcontext -D -N\n\" | /usr/sbin/semanage -i -", 
            "_uses_shell": true, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }, 
        "module_name": "command"
    }, 
    "rc": 1, 
    "start": "2017-08-29 14:14:51.430829", 
    "stderr": "SELinux:  Could not downgrade policy file /etc/selinux/targeted/policy/policy.24, searching for an older version.\nSELinux:  Could not open policy file <= /etc/selinux/targeted/policy/policy.24:  No such file or directory\nlibsemanage.semanage_reload_policy: load_policy returned error code 2.\nSELinux:  Could not downgrade policy file /etc/selinux/targeted/policy/policy.24, searching for an older version.\nSELinux:  Could not open policy file <= /etc/selinux/targeted/policy/policy.24:  No such file or directory\nlibsemanage.semanage_reload_policy: load_policy returned error code 2.\n/usr/sbin/semanage: Could not commit semanage transaction", 
    "stdout": "", 
    "stdout_lines": [], 
    "warnings": []
}
```

This comes from pull request #2. I have no idea why it passed on semaphore. I'll investigate.

@bachradsusi, do you have an idea why this might fail?

**Comment by bachradsusi** [comment]
This is the error pull request #2 tried to fix. Where did it come from? Is it Red Hat Enterprise Linux or Fedora? It seems that it came from a system with disabled SELinux or maybe other constrain.

**Comment by larskarlitski** [comment]
> Is it Red Hat Enterprise Linux or Fedora?

It happens on CentOS 6.

**Comment by bachradsusi** [comment]
I'm not able to reproduce it manually on CentOS-6-x86_64-GenericCloud-1702.qcow2c. But it's reproducible using run_test.sh or using cockpit/linux-system-roles-test container. I need to investigate it more.

**Comment by bachradsusi** [comment]
The reproducer is:

    $ ansible-playbook -u admin -i localhost:2222, --ssh-common-args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" test_selinux_disabled.yml
    PLAY RECAP ************************************************************************************                                                                                                
    localhost                  : ok=16   changed=12   unreachable=0    failed=0                 
    
    $ ansible-playbook -u admin -i localhost:2222, --ssh-common-args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" test_login.yml
    PLAY RECAP ************************************************************************************
    localhost                  : ok=12   changed=9    unreachable=0    failed=0
    
    $ ansible-playbook -u admin -i localhost:2222, --ssh-common-args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" test_selinux_disabled.yml
    TASK [selinux : Drop all local modifications] *************************************************
    fatal: [localhost]: FAILED! => {"changed": true, "cmd": "echo -e \"boolean -D -N\nlogin -D -N\nport -D -N\nfcontext -D -N\n\" | /usr/sbin/semanage -i -" ...

So some change made by `test_login.yml` makes `semanage` command to be unable to work in SELinux disabled environment.

**Comment by pcahyna** [comment]
@larskarlitski do you have any idea why it passed on semaphore?

**Comment by larskarlitski** [comment]
> @larskarlitski do you have any idea why it passed on semaphore?

No, sorry.

I also don't understand how `test_login` could influence `test_selinux_disabled`. They should run on a fresh VM each, no?

**Comment by bachradsusi** [comment]
According to my observation, all `test/test*yml` playbooks are run on the same image.

I've updated tests to clean up changes made by the role during testing.

**Comment by pcahyna** [comment]
@larskarlitski 
> I also don't understand how test_login could influence test_selinux_disabled. They should run on a fresh VM each, no?
This would explain why semaphore did not catch the bug. For the bug to manifest, it was actually necessary to have some modifications done before test_selinux_disabled.
@bachradsusi now updated the tests to catch the bug even without previous modifications, in #5. And hey presto, semaphore is failing properly.

**Comment by larskarlitski** [comment]
> And hey presto, semaphore is failing properly.

Ah, that's good to know. I've suggested changing the fedora testing spec to allow us to run more than one test independently so that we'll continue catching these bugs going forward.

Thanks for tracking this down!
