### ISSUE TITLE
move selogin module upstream

### ISSUE THREAD

**Issue by jamescassell** [linux-system-roles/selinux#34]
It would be useful to be able to make use of the 'selogin' module in vanilla ansible.  Are there any barriers to getting this module merged upstream?

**Comment by wrabcak** [comment]
I'm not aware of any barriers to put it to upstream, however Petr is author of the selogin module.

**Comment by bachradsusi** [comment]
I'm fine with that. Do you want me to do that or do you want to push it yourself?

**Comment by jamescassell** [comment]
I'd love it if you pushed the module upstream.  I don't have any bandwith to do it myself at the moment.

**Comment by jamescassell** [comment]
I've submitted a PR upstream to add the selogin module: https://github.com/ansible/ansible/pull/53960

If any of you have a chance to give it a quick look and a `shipit` if it looks good to you, I'd appreciate it.

@bachradsusi @wrabcak do either of you want to be listed as maintainers on the ansible side?

@bachradsusi and @dankeder are listed as authors and will automatically be listed as maintainers, unless I tell ansibot not to bother them with this module.

**Comment by bachradsusi** [comment]
https://github.com/linux-system-roles/selinux/pull/55

**Comment by spetrosi** [comment]
Closing as this issue has been resolved
