### ISSUE TITLE
RFE: ability to apply a SELinux policy module on multiple machines

### ISSUE THREAD

**Issue by milosmalik** [linux-system-roles/selinux#42]
Imagine a situation when customer is facing a problem that can be easily solved by loading a local policy module. Waiting for an official fix may not be acceptable, because customer day-to-day operations are affected.

The problem with manual application of a policy module (which works around the problem) to multiple machines can introduce errors.

Basically I'm looking for a way how to load/unload/enable/disable a local policy module on multiple machines. Similar concept to enabling/disabling of SELinux booleans.

**Comment by wrabcak** [comment]
Looks good me. It make sense to implement this.

**Comment by jaedolph** [comment]
Also very interested in this feature. In the past I have used the Selinux puppet module for this purpose that has some good features like being able to compile modules from source .te files or using pre compiled .pp files (https://github.com/voxpupuli/puppet-selinux/blob/master/manifests/module.pp)

Thinking it would be nice for a list of filenames to be passed to the role in something like:
```yaml
selinux_modules_pp:
- custom_policy1.pp
selinux_modules_te:
- custom_policy2.te
- custom_policy3.te
```

I would be happy to have a go implementing this and do a PR

**Comment by jaedolph** [comment]
I made a start on this, but then realised someone has already made a PR for a 'semodule' module in the main ansible repo! https://github.com/ansible/ansible/pull/66555

**Comment by bandit145** [comment]
@jaedolph I have closed that PR for now (because of the upcoming switch to collections), I will be getting that module submitted to the upcoming community collection as soon as that's possible.

**Comment by bandit145** [comment]
Sorry this took so long but I have the PR into the new community.general collection for Ansible. 
https://github.com/ansible-collections/community.general/pull/404

**Comment by bachradsusi** [comment]
See https://github.com/linux-system-roles/selinux/pull/56
