### ISSUE TITLE
Links in README.md are broken.

### ISSUE THREAD

**Issue by nhosoi** [linux-system-roles/selinux#83]
The URLs in README.md do not exist.
[selinux](http://docs.ansible.com/ansible/selinux_module.html)
[seboolean](http://docs.ansible.com/ansible/seboolean_module.html)
[seport](http://docs.ansible.com/ansible/seport_module.html)

Clicking them fails with:
```
The version of the Ansible documentation you were looking at doesn’t contain that page.
Cowsay 404

Use the back button to return to the version you were browsing, or use the navigation at left to explore our latest release. Once you’re on a non-404 page, you can use the version-changer to select a version.
```
These URLs exist:
https://docs.ansible.com/ansible/2.9/modules/selinux_module.html
https://docs.ansible.com/ansible/latest/collections/ansible/posix/selinux_module.html
https://docs.ansible.com/ansible/latest/collections/ansible/posix/seboolean_module.html
https://docs.ansible.com/ansible/latest/collections/ansible/posix/seboolean_module.html
https://docs.ansible.com/ansible/2.9/modules/seport_module.html
https://docs.ansible.com/ansible/latest/collections/community/general/seport_module.html

Also, selinux-playbook.yml has been moved to the examples directory.
[selinux-playbook.yml](selinux-playbook.yml)

Note: relative links are not rendered correctly on AH.

**Comment by richm** [comment]
looks like this was fixed some time ago
