### ISSUE TITLE
rename `SELinux_*` variables to lower case prefix 

### ISSUE THREAD

**Issue by bachradsusi** [linux-system-roles/selinux#9]
Other roles use lowercase variables and this change will make the role consistent with others.
The following variables should be changed:
* SELinux_type
* SELinux_mode
* SELinux_change_running
* SELinux_booleans
* SELinux_file_contexts
* SELinux_restore_dirs
* SELinux_ports
* SELinux_logins

**Comment by pcahyna** [comment]
When we are going to do such renames, it would make sense to rename them to be more consistent with other SELinux roles in Galaxy. I will add concrete examples.

**Comment by wrabcak** [comment]
Hi @pcahyna, 

I would like to  create PR here, could you add examples from your comment? 

Thanks,
Lukas.
